# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ReservationsData import ReservationsData
from RoomsData import RoomsData


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1200, 800)
        MainWindow.setStyleSheet("background-color: #222831;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QPushButton {\n"
                                         "    background-color: #393e46;\n"
                                         "    border: 2px solid #00adb5;\n"
                                         "    border-radius: 20px;\n"
                                         "    color: #eeeeee;\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover {\n"
                                         "    background-color: #4a4f57;\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 1181, 751))
        self.stackedWidget.setObjectName("stackedWidget")
        self.menu = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menu.setFont(font)
        self.menu.setStyleSheet("QLabel {\n"
                                "    color: #00adb5;\n"
                                "    font-size: 84px;\n"
                                "}\n"
                                "\n"
                                "QPushButton {\n"
                                "    font-size: 32px;\n"
                                "}\n"
                                "\n"
                                "")
        self.menu.setObjectName("menu")
        self.roomsButton = QtWidgets.QPushButton(self.menu)
        self.roomsButton.setGeometry(QtCore.QRect(440, 210, 311, 121))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.roomsButton.setFont(font)
        self.roomsButton.setObjectName("roomsButton")
        self.menuLabel = QtWidgets.QLabel(self.menu)
        self.menuLabel.setGeometry(QtCore.QRect(450, 60, 291, 81))
        self.menuLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.menuLabel.setObjectName("menuLabel")
        self.reservationsButton = QtWidgets.QPushButton(self.menu)
        self.reservationsButton.setGeometry(QtCore.QRect(440, 360, 311, 121))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.reservationsButton.setFont(font)
        self.reservationsButton.setObjectName("reservationsButton")
        self.quitButton = QtWidgets.QPushButton(self.menu)
        self.quitButton.setGeometry(QtCore.QRect(440, 510, 311, 121))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.quitButton.setFont(font)
        self.quitButton.setObjectName("quitButton")
        self.stackedWidget.addWidget(self.menu)
        self.rooms = QtWidgets.QWidget()
        self.rooms.setStyleSheet("QPushButton {\n"
                                 "    font-size: 24px;\n"
                                 "}\n"
                                 "\n"
                                 "QLineEdit {\n"
                                 "    padding: 5px;\n"
                                 "    border: 2px solid #ccc;\n"
                                 "    border-radius: 20px;\n"
                                 "    color: #eeeeee;\n"
                                 "    font-size: 24px;\n"
                                 "}\n"
                                 "\n"
                                 "QLabel {\n"
                                 "    padding-left: 10px;\n"
                                 "    color: #eeeeee;\n"
                                 "    font-size: 24px;\n"
                                 "}\n"
                                 "\n"
                                 "QComboBox {\n"
                                 "    padding-left: 10px;\n"
                                 "    border: 2px solid #ccc;\n"
                                 "    color: #eeeeee;\n"
                                 "    font-size: 24px;\n"
                                 "}\n"
                                 "\n"
                                 "QListView {\n"
                                 "    color: #eeeeee;\n"
                                 "}\n"
                                 "\n"
                                 "QListWidget {\n"
                                 "    color: #eeeeee;\n"
                                 "    font-size: 24px;\n"
                                 "}")
        self.rooms.setObjectName("rooms")
        self.showAvailableRoomsButton = QtWidgets.QPushButton(self.rooms)
        self.showAvailableRoomsButton.setGeometry(QtCore.QRect(390, 280, 401, 51))
        self.showAvailableRoomsButton.setObjectName("showAvailableRoomsButton")
        self.startDateLabel = QtWidgets.QLabel(self.rooms)
        self.startDateLabel.setGeometry(QtCore.QRect(160, 130, 131, 31))
        self.startDateLabel.setObjectName("startDateLabel")
        self.endDateLabel = QtWidgets.QLabel(self.rooms)
        self.endDateLabel.setGeometry(QtCore.QRect(160, 210, 131, 31))
        self.endDateLabel.setObjectName("endDateLabel")
        self.sortByLabelRooms = QtWidgets.QLabel(self.rooms)
        self.sortByLabelRooms.setGeometry(QtCore.QRect(640, 130, 131, 31))
        self.sortByLabelRooms.setObjectName("sortByLabelRooms")
        self.sortByComboBoxRooms = QtWidgets.QComboBox(self.rooms)
        self.sortByComboBoxRooms.setGeometry(QtCore.QRect(790, 120, 221, 51))
        self.sortByComboBoxRooms.setObjectName("sortByComboBoxRooms")
        self.sortByComboBoxRooms.addItem("")
        self.sortByComboBoxRooms.addItem("")
        self.sortByComboBoxRooms.addItem("")
        self.backToMenuButtonRooms = QtWidgets.QPushButton(self.rooms)
        self.backToMenuButtonRooms.setGeometry(QtCore.QRect(390, 10, 401, 51))
        self.backToMenuButtonRooms.setObjectName("backToMenuButtonRooms")
        self.bookSelectedRoomButton = QtWidgets.QPushButton(self.rooms)
        self.bookSelectedRoomButton.setGeometry(QtCore.QRect(610, 690, 401, 51))
        self.bookSelectedRoomButton.setObjectName("bookSelectedRoomButton")
        self.sortOrderLabelRooms = QtWidgets.QLabel(self.rooms)
        self.sortOrderLabelRooms.setGeometry(QtCore.QRect(640, 210, 131, 31))
        self.sortOrderLabelRooms.setObjectName("sortOrderLabelRooms")
        self.sortOrderComboBoxRooms = QtWidgets.QComboBox(self.rooms)
        self.sortOrderComboBoxRooms.setGeometry(QtCore.QRect(790, 200, 221, 51))
        self.sortOrderComboBoxRooms.setObjectName("sortOrderComboBoxRooms")
        self.sortOrderComboBoxRooms.addItem("")
        self.sortOrderComboBoxRooms.addItem("")
        self.roomsListWidget = QtWidgets.QListWidget(self.rooms)
        self.roomsListWidget.setGeometry(QtCore.QRect(160, 360, 861, 301))
        self.roomsListWidget.setObjectName("roomsListWidget")
        self.startDateLineEdit = QtWidgets.QLineEdit(self.rooms)
        self.startDateLineEdit.setGeometry(QtCore.QRect(310, 120, 221, 51))
        self.startDateLineEdit.setObjectName("startDateLineEdit")
        self.endDateLineEdit = QtWidgets.QLineEdit(self.rooms)
        self.endDateLineEdit.setGeometry(QtCore.QRect(310, 200, 221, 51))
        self.endDateLineEdit.setObjectName("endDateLineEdit")
        self.clientIdNumberLineEditRooms = QtWidgets.QLineEdit(self.rooms)
        self.clientIdNumberLineEditRooms.setGeometry(QtCore.QRect(160, 690, 401, 51))
        self.clientIdNumberLineEditRooms.setObjectName("clientIdNumberLineEditRooms")
        self.stackedWidget.addWidget(self.rooms)
        self.reservations = QtWidgets.QWidget()
        self.reservations.setStyleSheet("QPushButton {\n"
                                        "    font-size: 24px;\n"
                                        "}\n"
                                        "\n"
                                        "QLineEdit {\n"
                                        "    padding: 5px;\n"
                                        "    border: 2px solid #ccc;\n"
                                        "    border-radius: 20px;\n"
                                        "    color: #eeeeee;\n"
                                        "    font-size: 24px;\n"
                                        "}\n"
                                        "\n"
                                        "QLabel {\n"
                                        "    padding-left: 10px;\n"
                                        "    color: #eeeeee;\n"
                                        "    font-size: 24px;\n"
                                        "}\n"
                                        "\n"
                                        "QComboBox {\n"
                                        "    padding-left: 10px;\n"
                                        "    border: 2px solid #ccc;\n"
                                        "    color: #eeeeee;\n"
                                        "    font-size: 24px;\n"
                                        "}\n"
                                        "\n"
                                        "QListView {\n"
                                        "    color: #eeeeee;\n"
                                        "}\n"
                                        "\n"
                                        "QListWidget {\n"
                                        "    color: #eeeeee;\n"
                                        "    font-size: 14px;\n"
                                        "}")
        self.reservations.setObjectName("reservations")
        self.backToMenuButtonReservations = QtWidgets.QPushButton(self.reservations)
        self.backToMenuButtonReservations.setGeometry(QtCore.QRect(390, 10, 401, 51))
        self.backToMenuButtonReservations.setObjectName("backToMenuButtonReservations")
        self.sortByLabelReservations = QtWidgets.QLabel(self.reservations)
        self.sortByLabelReservations.setGeometry(QtCore.QRect(640, 130, 131, 31))
        self.sortByLabelReservations.setObjectName("sortByLabelReservations")
        self.showAllReservationsButton = QtWidgets.QPushButton(self.reservations)
        self.showAllReservationsButton.setGeometry(QtCore.QRect(640, 280, 371, 51))
        self.showAllReservationsButton.setObjectName("showAllReservationsButton")
        self.sortByComboBoxReservations = QtWidgets.QComboBox(self.reservations)
        self.sortByComboBoxReservations.setGeometry(QtCore.QRect(790, 120, 221, 51))
        self.sortByComboBoxReservations.setObjectName("sortByComboBoxReservations")
        self.sortByComboBoxReservations.addItem("")
        self.sortByComboBoxReservations.addItem("")
        self.sortByComboBoxReservations.addItem("")
        self.cancelSelectedReservationButton = QtWidgets.QPushButton(self.reservations)
        self.cancelSelectedReservationButton.setGeometry(QtCore.QRect(390, 690, 401, 51))
        self.cancelSelectedReservationButton.setObjectName("cancelSelectedReservationButton")
        self.searchClientReservationsButton = QtWidgets.QPushButton(self.reservations)
        self.searchClientReservationsButton.setGeometry(QtCore.QRect(170, 280, 431, 51))
        self.searchClientReservationsButton.setObjectName("searchReservationButton")
        self.clientIdNumberLabel = QtWidgets.QLabel(self.reservations)
        self.clientIdNumberLabel.setGeometry(QtCore.QRect(170, 210, 201, 31))
        self.clientIdNumberLabel.setObjectName("clientIdNumberLabel")
        self.sortOrderLabelReservations = QtWidgets.QLabel(self.reservations)
        self.sortOrderLabelReservations.setGeometry(QtCore.QRect(640, 210, 131, 31))
        self.sortOrderLabelReservations.setObjectName("sortOrderLabelReservations")
        self.sortOrderComboBoxReservations = QtWidgets.QComboBox(self.reservations)
        self.sortOrderComboBoxReservations.setGeometry(QtCore.QRect(790, 200, 221, 51))
        self.sortOrderComboBoxReservations.setObjectName("sortOrderComboBoxReservations")
        self.sortOrderComboBoxReservations.addItem("")
        self.sortOrderComboBoxReservations.addItem("")
        self.reservationsListWidget = QtWidgets.QListWidget(self.reservations)
        self.reservationsListWidget.setGeometry(QtCore.QRect(160, 360, 861, 301))
        self.reservationsListWidget.setObjectName("reservationsListWidget")
        self.clientIdNumberLineEditReservations = QtWidgets.QLineEdit(self.reservations)
        self.clientIdNumberLineEditReservations.setGeometry(QtCore.QRect(390, 200, 211, 51))
        self.clientIdNumberLineEditReservations.setPlaceholderText("")
        self.clientIdNumberLineEditReservations.setObjectName("clientIdNumberLineEditReservations")
        self.stackedWidget.addWidget(self.reservations)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.reservations_data = ReservationsData()
        self.rooms_data = RoomsData()
        self.selected_room = ''
        self.selected_reservation = ''

        self.backToMenuButtonReservations.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0))
        self.backToMenuButtonRooms.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(0))
        self.roomsButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(1))
        self.reservationsButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2))
        self.quitButton.clicked.connect(lambda: sys.exit())

        self.showAvailableRoomsButton.clicked.connect(self.show_available_rooms)
        self.showAllReservationsButton.clicked.connect(self.show_all_reservations)
        self.searchClientReservationsButton.clicked.connect(self.show_client_reservations)
        self.bookSelectedRoomButton.clicked.connect(self.book_selected_room)
        self.cancelSelectedReservationButton.clicked.connect(self.cancel_selected_reservation)
        self.roomsListWidget.itemClicked.connect(self.set_selected_room)
        self.reservationsListWidget.itemClicked.connect(self.set_selected_reservation)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RoomBooking"))
        self.roomsButton.setText(_translate("MainWindow", "Rooms"))
        self.menuLabel.setText(_translate("MainWindow", "MENU"))
        self.reservationsButton.setText(_translate("MainWindow", "Reservations"))
        self.quitButton.setText(_translate("MainWindow", "Quit"))
        self.showAvailableRoomsButton.setText(_translate("MainWindow", "Show available rooms"))
        self.startDateLabel.setText(_translate("MainWindow", "Start date"))
        self.endDateLabel.setText(_translate("MainWindow", "End date"))
        self.sortByLabelRooms.setText(_translate("MainWindow", "Sort by"))
        self.sortByComboBoxRooms.setItemText(0, _translate("MainWindow", "Room number"))
        self.sortByComboBoxRooms.setItemText(1, _translate("MainWindow", "Capacity"))
        self.sortByComboBoxRooms.setItemText(2, _translate("MainWindow", "Price"))
        self.backToMenuButtonRooms.setText(_translate("MainWindow", "Back to menu"))
        self.bookSelectedRoomButton.setText(_translate("MainWindow", "Book selected room"))
        self.sortOrderLabelRooms.setText(_translate("MainWindow", "Sort order"))
        self.sortOrderComboBoxRooms.setItemText(0, _translate("MainWindow", "Ascending"))
        self.sortOrderComboBoxRooms.setItemText(1, _translate("MainWindow", "Descending"))
        self.startDateLineEdit.setPlaceholderText(_translate("MainWindow", "YYYY-MM-DD"))
        self.endDateLineEdit.setPlaceholderText(_translate("MainWindow", "YYYY-MM-DD"))
        self.clientIdNumberLineEditRooms.setPlaceholderText(_translate("MainWindow", "Client ID number"))
        self.backToMenuButtonReservations.setText(_translate("MainWindow", "Back to menu"))
        self.sortByLabelReservations.setText(_translate("MainWindow", "Sort by"))
        self.showAllReservationsButton.setText(_translate("MainWindow", "Show all reservations"))
        self.sortByComboBoxReservations.setItemText(0, _translate("MainWindow", "Client ID number"))
        self.sortByComboBoxReservations.setItemText(1, _translate("MainWindow", "Room number"))
        self.sortByComboBoxReservations.setItemText(2, _translate("MainWindow", "Start date"))
        self.cancelSelectedReservationButton.setText(_translate("MainWindow", "Cancel selected reservation"))
        self.searchClientReservationsButton.setText(_translate("MainWindow", "Search"))
        self.clientIdNumberLabel.setText(_translate("MainWindow", "Client ID number"))
        self.sortOrderLabelReservations.setText(_translate("MainWindow", "Sort order"))
        self.sortOrderComboBoxReservations.setItemText(0, _translate("MainWindow", "Ascending"))
        self.sortOrderComboBoxReservations.setItemText(1, _translate("MainWindow", "Descending"))

    def show_available_rooms(self):
        self.roomsListWidget.clear()
        start_date = self.startDateLineEdit.text()
        end_date = self.endDateLineEdit.text()
        sort_by = self.sortByComboBoxRooms.currentText()
        sort_order = self.sortOrderComboBoxRooms.currentText()
        available_rooms = []

        try:
            rooms = self.rooms_data.get_sorted(sort_order, sort_by)
            available_rooms = self.reservations_data.get_vacant_rooms(rooms, start_date, end_date)
        except ValueError:
            pass

        for room in available_rooms:
            self.roomsListWidget.addItem(str(room))

    def show_all_reservations(self):
        self.reservationsListWidget.clear()
        sort_by = self.sortByComboBoxReservations.currentText()
        sort_order = self.sortOrderComboBoxReservations.currentText()

        try:
            reservations = self.reservations_data.get_sorted(sort_order, sort_by)
        except ValueError:
            pass

        for reservation in reservations:
            self.reservationsListWidget.addItem(str(reservation))

    def show_client_reservations(self):
        self.reservationsListWidget.clear()
        client_id_number = self.clientIdNumberLineEditReservations.text()

        reservations = self.reservations_data.get_client_reservations(client_id_number)

        for reservation in reservations:
            self.reservationsListWidget.addItem(str(reservation))

    def book_selected_room(self):
        if self.selected_room == '':
            return
        client_id_number = self.clientIdNumberLineEditRooms.text()
        room_number = self.selected_room.split()[2]
        start_date = self.startDateLineEdit.text()
        end_date = self.endDateLineEdit.text()

        if client_id_number != '' and room_number != '' and start_date != '' and end_date != '':
            try:
                self.reservations_data.add_reservation(client_id_number, room_number, start_date, end_date)
            except ValueError:
                pass
            else:
                self.show_available_rooms()

    def cancel_selected_reservation(self):
        if self.selected_reservation == '':
            return
        room_number = self.selected_reservation.split()[6]
        start_date = self.selected_reservation.split()[9]
        end_date = self.selected_reservation.split()[12]

        try:
            self.reservations_data.remove_reservation(room_number, start_date, end_date)
        except ValueError:
            pass
        else:
            self.show_all_reservations()

    def set_selected_room(self, item):
        self.selected_room = item.text()

    def set_selected_reservation(self, item):
        self.selected_reservation = item.text()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
